project_id = "vvkmdaesochqkahscezp"

[functions.tonviewer-api]
verify_jwt = false

[functions.get-device-info]
verify_jwt = false

[functions.daily-weekly-reset]
verify_jwt = false

[functions.detect-vpn]
verify_jwt = false

[functions.booster-cleanup]
verify_jwt = false

[functions.admin-panel]
verify_jwt = false