// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rsmgzhcniugipmektztq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzbWd6aGNuaXVnaXBtZWt0enRxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwNzQzNzEsImV4cCI6MjA3MzY1MDM3MX0.L43mgdhefrDC-unigJUhbVibfiHOV3a3D5ER7RDw-js";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});